#!/bin/bash
# A setup script to install shadovim fast and easy!

# List of CoC Plugins to install, add or remove what you want.
coc_list="coc-clangd coc-pairs coc-rls coc-rust-analyzer coc-sh coc-tabnine coc-yank coc-snippets coc-vimlsp"

# Install packer the top lua plugin manager for new neovim
echo "*== | Installing packer | ==*"
if [[ ! -d "~/.local/share/nvim/site/pack/packer/start/packer.nvim" ]]; then
    git clone --depth 1 https://github.com/wbthomason/packer.nvim\
     ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    if [[ $? -ne 0 ]]; then
        echo "<== | Error: Cloning packer repositiory failed | ==>"
        echo " -- Check your internet conneciton, and try again --"
        exit 1
    fi
else
    echo "*== | Packer already installed | ==*"
fi

# Install all packer packages with PackerSync from inside nvim
echo "*== | Installing packer plugins |==*"
echo " -- NVim will open to install some packer plugins in a second. --"
echo " -- When it is complete, exit nvim (q). Setup will resume after --"
echo " --- Hit ENTER to continue... ---"
read input
nvim -c ":PackerSync"
echo "#== | If that failed, rerun this script (Ctrl+c), else hit ENTER to continue... | ==#"
read input

# Install CoC Plugins
if [[ ! -z $coc_list ]]; then
    echo "*== | Installing CoC plugins | ==*"
    echo " -- Remember to exit when complete --"
    echo " --- Hit ENTER to continue... ---"
    read input
    nvim -c ":CocInstall ${coc_list}"
    echo "#== | If that failed, rerun this script (Ctrl+c), else hit ENTER to continue... | ==#"
    read input
fi

# Overwrite with a link my colorscheme on top of existing default one for lightline.vim
echo "*== | Installing lightline.vim theme | ==*"
ln -sf ~/.config/nvim/shado_lightline.vim ~/.local/share/nvim/site/pack/packer/opt/lightline.vim/autoload/lightline/colorscheme/deus.vim
if [[ $? -ne 0 ]]; then
    echo "<== | Error: failed to link colorscheme file | ==>"
    exit 1
fi
