#!/bin/bash
# A setup script to install shadovim fast and easy!

# Install packer the top lua plugin manager for new neovim
echo "*== | Installing packer | ==*"
if [[ ! -d "~/.local/share/nvim/site/pack/packer/start/packer.nvim" ]]; then
    git clone --depth 1 https://github.com/wbthomason/packer.nvim\
     ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    if [[ $? -ne 0 ]]; then
        echo "<== | Error: Cloning packer repositiory failed | ==>"
        echo " -- Check your internet connection, and try again --"
        exit 1
    fi
else
    echo "*== | Packer already installed | ==*"
fi

# Install all packer packages with PackerSync from inside nvim
echo "*== | Installing packer plugins |==*"
echo " -- Nvim will open to install some packer plugins in a second. --"
echo " -- When it is complete, exit nvim (:q). Setup will resume after --"
echo " --- Hit ENTER to continue... ---"
read input
nvim -c ":PackerSync"
echo "#== | If that failed, rerun this script (Ctrl+c), else hit ENTER to continue... | ==#"
read input

# Add lualine theme to local lualine folder
echo "*== | Installing lualine.nvim theme | ==*"
cp -f ~/.config/nvim/shado.lua ~/.local/share/nvim/site/pack/packer/start/lualine.nvim/lua/lualine/themes/shado.lua
if [[ $? -ne 0 ]]; then
    echo "<== | Error: failed to copy colorscheme file | ==>"
    exit 1
fi
