#!/bin/bash
# A setup script to install shadovim fast and easy!

# Install packer the top lua plugin manager for new neovim
function install_packer {
    echo "*== | Installing packer | ==*"
    rm -rf ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    git clone --depth 1 https://github.com/wbthomason/packer.nvim\
     ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    if [[ $? -ne 0 ]]; then
        echo "<== | Error: Cloning packer repositiory failed | ==>"
        echo " -- Check your internet connection, and try again --"
        exit 1
    fi
}

# Install all packer packages with PackerSync from inside nvim
function packer_sync {
    echo "*== | Installing packer plugins |==*"
    echo " -- Nvim will open to install some packer plugins in a second. --"
    echo " -- When it is complete, exit nvim (:q). Setup will resume after --"
    echo " --- Hit ENTER to continue... ---"
    read input
    nvim -c ":PackerSync"
    echo "#== | If that failed, rerun this script (Ctrl+c), else hit ENTER to continue... | ==#"
    read input
}

function usage {
    echo "Usage: setup [OPTION]"
    echo "If no OPTION, install everything"
    echo " -h       show this menu"
    echo " -p       install Packer"
    echo " -P       run :PackerSync"
    exit 0
}

if [[ $# -ne 0 ]]; then
    while getopts 'lpPh' OPTION; do
        case "$OPTION" in
            p) install_packer;;
            P) packer_sync;;
            *|h|help) usage;;
        esac
    done
    exit 0
fi

# Default install
install_packer
packer_sync
